### ISSUE TITLE
1+1 does not equal 2 when using /calculate

### ISSUE THREAD

**Issue by Elite230** [Nexus-AI-Bot/Nexus.AI#15]
# 1+1 does not equal 2 when using `/calculate`
## **Description:**

Executing the command `/calculate` with the input of any equation would result in the bot writing `You wrote that wrong:(`.

This is a failure of the use of the library used.

## **Expected Behavior:**
I expected the answer to `1+1` to be `2`. Correct me if I'm wrong...

## **Actual Behavior:**

output for `/calculate math_problem:1+1` is `You wrote that wrong:(` not `2`

## **Steps to Reproduce:**

1. execute command in the [Official Discord server](https://discord.gg/XzytPbbuhW) in `#commands-1` (<#1085924162830344293>) `/calculate math_problem:1+1`

**Comment by Fluffik3666** [comment]
Do not pin error.
